# compose 파일 버전
version: "3"
services:
  # 서비스 명
  authrization:
    # 사용할 이미지
    image: hybriddevslim/authorization-server-2023:latest
    # 컨테이너 실행 시 재시작
    restart: always
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/authorization
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: redis
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECTURI: http://auth-server:9090/login/oauth2/code/kakao
    # 볼륨 설정
    volumes:
      - ./data/authorization/:/data
  # 서비스 명
  postgresql:
    # 사용할 이미지
    image: postgres:latest
    # 컨테이너 실행 시 재시작
    restart: always
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5432:5432"
    # 환경 변수 설정
    environment:
      # PostgreSQL 계정 및 패스워드 설정 옵션
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authorization
    # 볼륨 설정
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/data
      - ./conf/redis.conf:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf
