server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://resource-service:5002/authorization-service
          jwk-set-uri: http://resource-service:5002/authorization-service/oauth2/v1/jwks
      client:
        registration:
          sso: # registrationId
            client-id: chat-client
            client-secret: chat-secret
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            redirectUri: http://talk-client-server:8080/login/oauth2/code/sso
            scope:
              - openid
            clientName: sign in sso
        provider:
          sso:
            issuerUri: http://resource-service:5002/authorization-service
            authorizationUri: http://resource-service:5002/authorization-service/oauth2/v1/authorize
            tokenUri: http://resource-service:5002/authorization-service/oauth2/v1/token
            userInfoUri: http://resource-service:5002/authorization-service/connect/v1/userinfo
            jwkSetUri: http://resource-service:5002/authorization-service/oauth2/v1/jwks
            userNameAttribute: sub
  thymeleaf:
    suffix: .html
    mode: HTML
    cache: false
    check-template: false
    encoding: UTF-8
    template-resolver-order: 1

resource-client:
  baseUrl: http://resource-service:5002

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
