server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          sso: # registrationId
            client-id: chat-client
            client-secret: chat-secret
            clientAuthenticationMethod: client_secret_basic
            authorizationGrantType: authorization_code
            redirectUri: http://talk-client-server:8080/login/oauth2/code/sso
            scope:
              - openid
            clientName: sign in sso
        provider:
          sso:
            authorizationUri: http://auth-server:9090/oauth2/v1/authorize
            tokenUri: http://auth-server:9090/oauth2/v1/token
            userInfoUri: http://auth-server:9090/connect/v1/userinfo
            jwkSetUri: http://auth-server:9090/oauth2/v1/jwks
            userNameAttribute: sub

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
